apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: acedemo-git
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/sreckoj/ACE-CI-CD-Demo-Tekton.git
